name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: "Build Artifact"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: './gradlew clean shadowJar'
  release:
    name: "Release Artifact"
    runs-on: "ubuntu-latest"
    needs: build

    steps:
      - name: GitHub Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/libs/*.jar
      - name: Trigger JitPack
        run: curl "https://jitpack.io/com/github/TeamSkyBeach/Stracciatella/${GITHUB_SHA:0:10}/build.log"